// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uslontbfisvmtqtneiri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzbG9udGJmaXN2bXRxdG5laXJpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MzQyMzIsImV4cCI6MjA1MDIxMDIzMn0.D2_KhcTmCKgmh52Pv90dW9-K_djZ6REtUdr46O_tYys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);